### ISSUE TITLE
Microsoft Bot Framework Support

### ISSUE THREAD

**Issue by wiltodelta** [dialogflow/dialogflow-dotnet-client#1]
Do you plan to support Microsoft Bot Framework?

**Comment by xVir** [comment]
Hi, @wiltodelta 
In what kind of support you are interested?

From the [docs](http://docs.botframework.com/connector/getstarted/), it seems, the library can be used from [ApiController](http://docs.botframework.com/connector/getstarted/#building-your-bot) without additional modifications. 
Or did you mean another options?

Thanks.

**Comment by wiltodelta** [comment]
I think about ApiApiDialog like LuisDialog:
https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Samples/SimpleAlarmBot/SimpleAlarmDialog.cs

**Comment by xVir** [comment]
Yes, looks great,

I think we will add this to future plans.  
In any case feel free to make a pull request.

Thanks!

**Comment by brunobrandes** [comment]
Hello guys.
I published an example using api.ai in a Bot Application project on [github](https://github.com/brunobrandes/api-ai-csharp)
I'm enjoying learning about [api.ai](https://api.ai/)

**Comment by xVir** [comment]
Hi, @brunobrandes 

Great! Thanks you a lot!!! 👍

**Comment by sunithabist** [comment]
hi, @brunobrandes 

I would like to know how to use api.ai instead of luis.ai NPL in microsoft bot framework..

**Comment by brunobrandes** [comment]
@sunithabist 
Do you did see samples on this [link](https://github.com/brunobrandes/api-ai-csharp) ?

**Comment by sunithabist** [comment]
yup.. but I need pictured responses.. can I do with api.ai or Do you know how to use two luis model in c#(since in luis.ai intents are limited to 20 only).

**Comment by obirije** [comment]
Please I would really love api.ai-node to connect to Microsoft Bit Framework for Nodejs

**Comment by GanadiniAkshay** [comment]
I recently published an npm module to use api.ai instead of LUIS in microsoft bot framework
https://www.npmjs.com/package/api-ai-recognizer

**Comment by giorgobiani** [comment]
I would also like "native" support of MS bot framework. How they are working using LUIS is very comfortable and something like that, but for API.AI would be just great!

**Comment by sunithabist** [comment]
Can't  I use C# for api.ai in Microsoft Bot framework

**Comment by sunithabist** [comment]
hi, @brunobrandes

I seen the link but it was running using node js but i need api.ai to be implemented in C#.. In that link where I can find controller code and class file for api.ai

**Comment by giorgobiani** [comment]
@sunithabist there's [official nuget package](https://www.nuget.org/packages/ApiAiSDK/), you can install it and directly call api.ai agents text or speech mode, you will get back full data including actions, fulfillment, context and etc.,
