### ISSUE TITLE
Remember Session

### ISSUE THREAD

**Issue by luuksuijkerbuijk** [dialogflow/dialogflow-dotnet-client#11]
I created a chatbot with de API.ai console.
I also created a dotnet project where I implemented api.ai with the SDK.

The bot answers the questions, but it doesn't remember the session.

When the client asks something and the bot response with a question for more information. The client gives the information, but then de bot doesn't know where it is about. But in the console it does work.

Example:
Client: I want to cook diner.
Bot: What ingredients do you want to use?
Client: Beef and brocolli.
Bot: I don't know what you mean.

Can anybody help my? How can I create something like a session?

**Comment by abhishan** [comment]
I am also facing the same issue. The context gets lost and each message sent is treated as a new one.

**Comment by abhishan** [comment]
I was able to make it work by setting the SessionID param in AIConfiguration. The code looks like this:
`var configuration = new AIConfiguration(AccessToken, SupportedLanguage.English);`
`configuration.SessionId = "MySessionID";`
`ApiAiClient = new ApiAi(configuration);`

According to docs (https://docs.api.ai/docs/query):
sessionId	(String) - A string token up to 36 symbols long, used to identify the client and to manage session parameters (including contexts) per client.

**Comment by xVir** [comment]
Hi @luuksuijkerbuijk 
Yes, you have to use only one instance of `ApiAi` class (like singleton) or you have to use some user related session id (generate and store it in application settings, for example).

For details you could take a look at the source code [here](https://github.com/api-ai/apiai-dotnet-client/blob/master/ApiAiSDK/AIDataService.cs#L43).

Thanks!

**Comment by Eptick** [comment]
This issue needs to be closed then?
