### ISSUE TITLE
.NET Portable Version

### ISSUE THREAD

**Issue by abrad1212** [dialogflow/dialogflow-dotnet-client#15]
I was wondering if there is ever going to be a .NET Portable version as I want to make a DLL containing all my apiai code, then have a class name `Actions` that contains all actions related to my chatbot, 

_So in theory a user could import this DLL and make a class inheriting the `Actions` class and override a specific action so their code runs when apiai returns an action_

**Comment by MovGP0** [comment]
I guess a .NET Standard-Version would be the better way to go
