### ISSUE TITLE
Dialogflow Fails to Parse "WebhookResponse"

### ISSUE THREAD

**Issue by AlexEales** [dialogflow/dialogflow-dotnet-client#33]
It seems that when returning a `WebhookResponse` from a .NET Core API to Google DialogFlow for fulfilment that the response is mangled and incorrectly parsed in some way. Below is the simple controller I have servicing the fulfilment request:

```c#
// POST api/dialogflow
[HttpPost]
public IActionResult FulfillDialogFlowRequest([FromBody] WebhookRequest request)
{
    var response = new WebhookResponse
    {
        FulfillmentText = "Hello from " + request.QueryResult.Intent.DisplayName
    };
    return Ok(response);
}
```

This should return the a blank `WebhookResponse` with the fulfilment text: `Hello from <intent name>` apon receiving any `WebhookRequest`. However, DialogFlow receives the following fulfilment response:

![image](https://user-images.githubusercontent.com/8074681/49871949-7d99dc00-fe0f-11e8-99e7-059e6c3c517a.png)

Whereby, every character is seperated by a space. This does not occur when run locally with the sample webhook request and even copying the text removes the spaces displayed here.

The error message for this suggests a parsing error: 

`Webhook call failed. Error: Failed to parse webhook JSON response: Expect message object but got: \"笀∀昀甀氀昀椀氀氀洀攀渀琀吀攀砀琀∀㨀∀䠀攀氀氀漀 昀爀漀洀 吀攀猀琀嘀愀氀甀攀猀∀Ⰰ∀昀甀氀昀椀氀氀洀攀渀琀䴀攀猀猀愀最攀猀∀㨀嬀崀Ⰰ∀猀漀甀爀挀攀∀㨀∀∀Ⰰ∀瀀愀礀氀漀愀搀∀㨀渀甀氀氀Ⰰ∀漀甀琀瀀甀琀䌀漀渀琀攀砀琀猀∀㨀嬀崀Ⰰ∀昀漀氀氀漀眀甀瀀䔀瘀攀渀琀䤀渀瀀甀琀∀㨀渀甀氀氀紀\".`

I've tried other methods to get this to work including returning the `WebhookResponse` object as a string or using Newtonsoft JSON to format the object as a JSON. I couldn't find a issue like this on here and couldn't find any samples that demonstrated this use case.

For added context, the API is being hosted on Azure and other controllers function properly when deployed, also below is my `.csproj` file to show versions of the various Nuget Packages etc.:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4"/>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1"/>
    <PackageReference Include="Google.Cloud.Dialogflow.V2" Version="1.0.0-beta02"/>
  </ItemGroup>
</Project>
```

If any other information is required or other snippets from my code please don't hesitate to ask and I will reply as soon as I can!

**Comment by Xavier-Josephh** [comment]
Hi Alex, Even I'm facing the same issue, have you got any work around for this? Thanks
